project:
  title: "{{< var site_title >}}"
  type: book
  output-dir: docs

execute:
  freeze: true
  
book:
  title: "{{< var course_num >}}: {{< var course_title >}} | {{< var academic_term >}} | {{< var cohort_type >}}"
  author: "Rafael C. Alvarado"
  date: "08/09/2023"
  reader-mode: false
  page-navigation: true
  repo-actions: [edit]
  repo-url: "https://github.com/ontoligent/DS5100-2023-08-O"
  chapters:
    - index.qmd 
    - part: modules/m01/m01-intro.qmd # "01 Getting Started"
      chapters:
        - topics/rivanna.qmd
        - topics/unix.qmd
        - topics/setting-up-ssh.qmd
        - topics/git-and-github.qmd
        - modules/m01/m01-using-rivanna.qmd
        - modules/m01/m01-activity-github.qmd
      appendices:
        - topics/oreilly-accounts.qmd
        - topics/refreshing-the-course-repo.qmd
    - part: modules/m02/m02-intro.qmd # "02 Introducing Python"
      chapters:
        - topics/on-data.qmd
        - topics/python-object-types.qmd
        - modules/m02/m02-activity-hello-world.qmd
        - modules/m02/m02-activity-jupyter-lab-on-rivanna.qmd
        - notebooks/M02_BasicPython/M02-01-DataTypes.ipynb
        - notebooks/M02_BasicPython/M02-02-Numbers.ipynb
        - notebooks/M02_BasicPython/M02-03-Booleans.ipynb
        - notebooks/M02_BasicPython/M02-04-Strings.ipynb
        - notebooks/M02_BasicPython/M02-05-Structures.ipynb
        - notebooks/M02_BasicPython/M02-Notes.ipynb
    - part: modules/m03/m03-intro.qmd # "03 Control Structures"
      chapters:
        - topics/vals-vars-expressions-statements.qmd
        - notebooks/M03_ControlStructures/M03-01-ControlStructures.ipynb
        - notebooks/M03_ControlStructures/M03-02-IterablesAndIterators.ipynb
        - notebooks/M03_ControlStructures/M03-03-Comprehensions.ipynb
    - part: modules/m04/m04-intro.qmd # "04 Functions"
      chapters: 
        - notebooks/M04_PythonFunctions/M04-02-Functions.ipynb
        - notebooks/M04_PythonFunctions/M04-01-Importing.ipynb
        - notebooks/M04_PythonFunctions/M04-03-LambdaFunctions.ipynb
        - notebooks/M04_PythonFunctions/M04-04-RecursiveFunctions.ipynb
        - notebooks/M04_PythonFunctions/M04-05-Scope.ipynb
        - notebooks/M04_PythonFunctions/M04-06-FunctionsCallingFunctions.ipynb
    - part: modules/m05/m05-intro.qmd # "05 NumPy"
      chapters:
        - notebooks/M05_NumPy/M05-02-NumpyBasics.ipynb
        - notebooks/M05_NumPy/M05-03-NumpyBasicsContinued.ipynb
        - notebooks/M05_NumPy/M05-00-Time.ipynb
        - notebooks/M05_NumPy/M05-01-BasicFileIO.ipynb
    - part: modules/m06/m06-intro.qmd # "06 Pandas"
      chapters:
        - notebooks/M06_Pandas/M06-01-Pandas1.ipynb
        - notebooks/M06_Pandas/M06-02-Pandas2.ipynb
        - notebooks/M06_Pandas/M06-03-NarrowWide.ipynb
        - notebooks/M06_Pandas/M06-04-MethodChaining.ipynb
        - notebooks/M06_Pandas/M06-05-Pandas-and-SQL.ipynb
    - part: modules/m07/m07-intro.qmd # "07 Classes"
      chapters: 
        - topics/what-is-oop.qmd      
        - notebooks/M07_PythonClasses/M07-01-Classes.ipynb
        - notebooks/M07_PythonClasses/M07-02-ClassesExample.ipynb
        - notebooks/M07_PythonClasses/M07-03-MoreOnClasses.ipynb
        - notebooks/M07_PythonClasses/M07-05-Example.ipynb
        - notebooks/M07_PythonClasses/M07-04-ClassAttributeWeirdness.ipynb
    - part: modules/m08/m08-intro.qmd # "08 Testing"
      chapters: 
        - modules/m08/m08-testing-and-verification.qmd
        - notebooks/M08_PythonTesting/M08-01-ExceptionHandling.ipynb 
        - notebooks/M08_PythonTesting/M08-02-PythonUnitTesting.ipynb
    - part: modules/m09/m09-intro.qmd # "09 Modules"
      chapters: 
        - notebooks/M09_PythonModules/M09-01-PackagesIntro.ipynb
        - notebooks/M09_PythonModules/M09-01a-Globals.ipynb
        - notebooks/M09_PythonModules/M09-02-MakingYourOwn.ipynb
        - notebooks/M09_PythonModules/M09-02a-InitPyDemo.ipynb
        - modules/m09/m09-review.qmd
    - part: modules/m10/m10-intro.qmd # "10 Basic R"
      chapters: 
        - notebooks/M10_RBasics/M10-01-DataTypesAndStructures.qmd
        - notebooks/M10_RBasics/M10-02-ControlStructuresAndFunctions.qmd
    - part: modules/m11/m11-intro.qmd # "11 Dplyr"
      chapters: 
        # - notebooks/M11_RDplyr/M11-00-Addenda.ipynb
        - notebooks/M11_RDplyr/M11-01-Tibbles.qmd
        - notebooks/M11_RDplyr/M11-02-Dplyr.qmd
    - part: modules/m12/m12-intro.qmd # "12 Visualization"
      chapters: 
        - notebooks/M12_RViz/M12-01-GGPlot.qmd
        - notebooks/M12_RViz/M12-02-RMarkdown.qmd
        - notebooks/M12_RViz/M12-03-Qplot-and-Plotly.ipynb
        - notebooks/M12_RViz/M12-04-Plotnine.ipynb
    - part: modules/m13/m13-intro.qmd # "13 Agile"
      chapters: 
        - topics/project-management.qmd
        - topics/agile-dev.qmd
        - topics/user-stories.qmd
        # - modules/m13/m13-activity.qmd
    - part: "Appendices"
      chapters: 
        - topics/oreilly-accounts.qmd
        - topics/refreshing-the-course-repo.qmd
  
  sidebar:
    style: docked
    reader-mode: false
    # style: floating
    background: light
    collapse-level: 1
    subtitle: Fall 2024

# comments:
#   hypothesis: true

format:
  html:
    toc: true
    theme: cosmo
    number-sections: false
    fig-cap-location: bottom
    link-external-icon: true
    link-external-newwindow: true
    reader-mode: false
  # pdf:
  #   documentclass: scrreport    

bibliography:
  - refs.bib
